services:
  rest:
    image: tabulario/iceberg-rest:0.11.0
    container_name: iceberg-rest
    networks: [iceberg_net]
    ports:
      - 8181:8181
    environment:
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_PATH_STYLE_ACCESS=true
      - CATALOG_S3_REGION=us-east-1
      - CATALOG_S3_ACCESS_KEY_ID=admin
      - CATALOG_S3_SECRET_ACCESS_KEY=password

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    networks: [iceberg_net]
    ports:
      - 9000:9000
      - 9001:9001
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    image: minio/mc
    container_name: mc
    depends_on: [minio]
    networks: [iceberg_net]
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      tail -f /dev/null
      "

  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on: [rest, minio]
    networks: [iceberg_net]
    ports:
      - 8080:8080
    volumes:
      - ./post-init.sql:/post-init.sql:ro
      - ./catalog/iceberg.properties:/etc/trino/catalog/iceberg.properties:ro

networks:
  iceberg_net:
    name: trino-iceberg
